### ISSUE TITLE
Unable to share screen/windows while in google meet

### ISSUE THREAD

**Issue by jcochran26** [RPi-Distro/chromium-browser#13]
As described, when using 64-bit RPI OS, I'm unable to share my screen or any windows while using Chromium.   Note that this works fine in FireFox ESR, so I tend to think the issue is with the browser, not the OS.

Also worth noting, and maybe related, my webcam microphone stays muted by default, and attempts to unmute it fail (it just mutes itself again).   Video works fine, however.   And, as before, this also works fine with FireFox ESR.

**Comment by XECDesign** [comment]
The 64 bit install doesn't use our build of chromium yet. This is straight from Raspbian/Debian.

**Comment by Roburetto** [comment]
This is also happening in RPI OS 32 bits (screen sharing is disabled) and is a serious problem.

chromium-browser/testing,now 86.0.4240.197-rpt1 armhf [installed]

There's an old Debian issue regarding "enable_hangout_services_extension" flag being disabled in rules, not sure if it relates: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886358

**Comment by XECDesign** [comment]
That flag should be enabled in the next release (for the armhf build).

**Comment by XECDesign** [comment]
Should be fixed in v88.
