### ISSUE TITLE
Hardware acceleration causes problems with PowerPoint Online Slideshow

### ISSUE THREAD

**Issue by wce-pi** [RPi-Distro/chromium-browser#14]
When hardware acceleration switch is enabled, text in PowerPoint slideshows (via Office 365 online) is rendered incorrectly.  This has been tested and seen with both 32-bit and 64-bit ARM distributions of Raspberry Pi OS on RPi 4 and RPi 400.  The issue does not exist in the x86 distribution.  Images are attached.  Let me know if there's anything I can test to help resolve.

PPT in Chromium - designer mode:
![20210108_195818](https://user-images.githubusercontent.com/77946867/105892701-36b3d400-5fe0-11eb-8230-b0244ba58042.jpg)

PPT in Chromium - slideshow:
![20210108_195344](https://user-images.githubusercontent.com/77946867/105892716-3e737880-5fe0-11eb-9e35-9e3d5519261c.jpg)

**Comment by Nabla128k** [comment]
Confirming this - it also affects Teams shared presentation - if remote side on windows shares a presentation thru teams, its displayed garbled as this

**Comment by XECDesign** [comment]
Is this still an issue with chromium-browser v95 in Bullseye?
