### ISSUE TITLE
Chromuim is crashing shortly after starting up - How can I diagnose?

### ISSUE THREAD

**Issue by toby-griffiths** [RPi-Distro/chromium-browser#17]
The Pi 400 I bought for my Mum for Xmas is no longer allowing her to use Chromium.  Every time she tries to launch it it crashed about 3-5 seconds after opening.  Not quite sure where to start looking on this one, other than remove & re-install.

Is anyone able advise how I might go about diagnosing the problem?  I'm not "on site", but should be able to screen share to access logs etc.

Please advise if there's a better place to ask this question.

**Comment by XECDesign** [comment]
Is this still an issue in v95 on Bullseye?
