### ISSUE TITLE
YouTube videos in Chromium sound like a cracked speaker

### ISSUE THREAD

**Issue by Botspot** [RPi-Distro/chromium-browser#18]
I've been having this problem for months. This seems to have started when Chromium was updated to version 88. It could be partially caused by pulseaudio.
The severity of cracking, popping, and buzzing seems to correlate with CPU usage.

Others have this issue too. https://www.raspberrypi.org/forums/viewtopic.php?p=1861857#p1861857
Another forum topic where a few members downgrade chromium to fix the issue: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=306919

**Comment by XECDesign** [comment]
@spl237 any idea about this? I haven't experienced it myself.

**Comment by talraash** [comment]
Add... Not only a youtube video. Any video(h264, vp9...) in browser(chromium) with resolution more than 480p. And cracking only with audio output via 3.5. Bluetooth output work fine.

**Comment by Botspot** [comment]
> And cracking only with audio output via 3.5.

Have we seen anyone who reports this issue happening with HDMI audio output?

**Comment by Botspot** [comment]
Any updates?

**Comment by pidd-wbiz** [comment]
It has been confirmed by a number of user that the distortion only happens on the jack output, hdmi output is fine.

**Comment by popcornmix** [comment]
Does `audio_pwm_mode=1` in config.txt help?

**Comment by talraash** [comment]
> Does `audio_pwm_mode=1` in config.txt help?

No, for me.

**Comment by pidd-wbiz** [comment]
> Does `audio_pwm_mode=1` in config.txt help?

Interesting, tried that a while ago and it made no difference, just tried it now and it fixes mine - doubly confirmed by removing it and it was straight back to Dalek voices.

**Comment by Botspot** [comment]
> Does `audio_pwm_mode=1` in config.txt help?

I tried it about a month ago and it made no difference.

**Comment by pidd-wbiz** [comment]
The sound quality of audio_pwm_mode=1 is poor compared to the normal mode in addition to get rid of the hiss you have to use disable_audio_dither=1.  Most voices now sound a little bit Donald Ducky and an underlying hiss still happens in bursts.

I wouldn't count audio_pwm_mode=1 as a fix but its an improvement to listening to cracked speakers.

**Comment by dhsim2000** [comment]
Hello, This is Future Dimension, 

we provide sposync.com to access to your device with
streaming and control using webRTC technology Free.

Only one required app is a web browser - Chromium and 
provided python websocket server on RPI.
(tested for Buster and Chromium 72) 

You can define the control command and extra security key if needed.
With these inputs, only you can access to your device remotely.
Please contact misdiva1bil@gmail.com 

Thanks,
David FDI
RPI 탑재 Chromium 활용 원격 접속 제어 및 스트리밍  서비스 무료 - 앱 개발전 간단한 제어 명령만 정의되면 기능등 시험 가능 sposync.com  https://youtu.be/3l2O2i6UX20
Free Video Ads, Event Hosting, P2P Call & Control

**Comment by XECDesign** [comment]
Last post in the linked thread seems to suggest the issue is now resolved?

https://forums.raspberrypi.com/viewtopic.php?t=309740&sid=d52181a432194ae1647ac5382a82a4a3&start=25#p1920341

**Comment by Botspot** [comment]
I'm not sure when something changed, but I haven't been having this problem in months. It was okay in buster before I moved to bullseye.
