### ISSUE TITLE
Raspicam not seen in chromium-browser after update

### ISSUE THREAD

**Issue by realjanek** [RPi-Distro/chromium-browser#23]
Hi
I have a problem with raspicam driver in Chromium web browser on RPi.
I created a new image and enable camera and did other setting.
When opening Chromium and going to this site https://webrtc.github.io/samples/ 
I see see my camera and microphone and I am able to run Basic getUserMedia demo and other examples from this site.
After RPi system update and upgrade and reboot, raspicam is not visible in Chromium browser.
How to fix it?
Jan

**Comment by realjanek** [comment]
more info:
following the instruction from here: viewtopic.php?t=308303
I'm trying to downgrade Chromium browser for RPi (I'm using Rpi3A+)
Which of the packages from here http://archive.raspberrypi.org/debian/p ... m-browser/
should I choose? With my guesses I have so far installation error.

**Comment by XECDesign** [comment]
Doesn't seem to work for me either.

@jc-kynesim, IIRC, there was a build flag for it, but I am having trouble digging up the information about it. Would you happen to remember what's needed?

**Comment by XECDesign** [comment]
Actually no, I was thinking of `enable_hangout_services_extension`, but that's to enable screen sharing and is already enabled.

**Comment by jc-kynesim** [comment]
The V4L2 camera driver may be broken in v92 - I looked into this in v95 where the camera advertises continuous sizes but chrome only likes a list of fixed sizes (chrome isn't the only thing that is confused by this).  I've got a (source) kludge for this, but other business took over my priorities before anything more happened.

**Comment by jc-kynesim** [comment]
Just to be clear, whilst what the V4L2 camera advertises is accurate as the ISP can do almost anything, but this could be "fixed" in the V4L2 driver if it picked a plausible list of resolutions rather than saying "I can do anything" with no hints as to what would be a good default. (If you ask for 0x0 which I would have hoped would give a default you get 32x32 which isn't helpful)

**Comment by XECDesign** [comment]
Alright, thanks for the explanation!

**Comment by andi34** [comment]
Any news on this? Camera access works in Chromium v88 while it fails on later versions (no request to allow camera access visible).
As workaround downgrade to v88 via Pi Apps
https://forums.raspberrypi.com/viewtopic.php?t=290329

**Comment by jc-kynesim** [comment]
Just to check - this is a Pi Camera, not a USB one? I'm mildly surprised that it works in v88 - when last seen the camera V4L2 compatibility layer was broken and that was one of the reasons nothing worked - yes, we should be using libcamera natively and I had a good go but fell into what looked like a deep, deep stdc++ vs libstdc++ link issue.  I'll revisit when I have a chance - maybe next week.

**Comment by andi34** [comment]
Hey and thanks for the reply. I was forwarding the issue, we had a discussion about the problem here
https://github.com/andreknieriem/photobooth/issues/296 (the Project is maintained at https://github.com/andi34/photobooth).

The workaround at least works on buster based Pi OS, can't tell about Bullseye.

I've sadly not had time yet to test myself, but there was another report about the issue in our Photobooth telegram group. My daughter was born end of august and currently I only sparely have time on a PC.

**Comment by andi34** [comment]
Silly question https://github.com/hisenyiu2015/msm-4.14/commit/fc02ed828d2910e5431526b60eece09a4a74d26c seems Not to be applied on v5.10.y https://github.com/raspberrypi/linux/blob/30bb91977d65c22cec3eaeadb06a6ff7f36ecbc5/drivers/media/platform/bcm2835/bcm2835-unicam.c#L121-L121
. Could this be related?

**Comment by jc-kynesim** [comment]
No. Thats not going to be it.
Now you've explained that you are on buster it all makes a bit more sense. Buster _does_ have a working camera V4L2 layer and v88 works with that, something got broken in Chrome after that going to v92 (probably "better" size checking), but then bullseye came out and the policy decision was that new versions of Chrome would only be ported to bullseye (it was getting to be an increasing pain to get a compatible lib set to compile on buster), buster would get the base debian port which doesn't have my V4L2 size kludge in it (v95 bullseye does).
This decision does have the unfortunate side effect that, as the V4L2 camera driver is bust in bullseye (or it was last I looked - it may have got better) and libcamera is currently problematic that Pi camera support is bust everywhere :-(
That isn't a helpful response I know, but I believe it to be a statement of where we are.

**Comment by andi34** [comment]
Thanks for the information! So there's nothing we can do on buster besides downgrading? 
Do your patches apply on newer chromium Versions which could be self complied?

**Comment by jc-kynesim** [comment]
If you are up for compiling chrome yourself then I'll certainly dig out the patch (its only a few lines - and if you want to tweak it then its function is pretty obvious)

**Comment by andi34** [comment]
That would be great. I think I've an old setup still on my desktop, I've compiled my own chromium for Android in the past.

**Comment by jc-kynesim** [comment]
v95 patch:
`diff --git a/src/media/capture/video/linux/video_capture_device_factory_linux.cc b/src/media/capture/video/linux/video_capture_device_factory_linux.cc
index 6724957d80aa7..3748d05f9f130 100644
--- a/src/media/capture/video/linux/video_capture_device_factory_linux.cc
+++ b/src/media/capture/video/linux/video_capture_device_factory_linux.cc
@@ -310,8 +310,25 @@ void VideoCaptureDeviceFactoryLinux::GetSupportedFormatsForV4L2BufferType(
       } else if (frame_size.type == V4L2_FRMSIZE_TYPE_STEPWISE ||
                  frame_size.type == V4L2_FRMSIZE_TYPE_CONTINUOUS) {
         // TODO(mcasas): see http://crbug.com/249953, support these devices.
-        NOTIMPLEMENTED_LOG_ONCE();
-        continue;
+//        NOTIMPLEMENTED_LOG_ONCE();
+//        continue;
+        // Kludge so we have some video
+        static const v4l2_frmsize_discrete sizes[] = {
+          {1280, 720},
+          {640, 360},
+          {320, 180}
+        };
+        for (const auto& size : sizes) {
+          supported_format.frame_size.SetSize(size.width, size.height);
+          const std::vector<float> frame_rates = GetFrameRateList(
+              fd, v4l2_format.pixelformat, size.width, size.height);
+          for (const auto& frame_rate : frame_rates) {
+            supported_format.frame_rate = frame_rate;
+            supported_formats->push_back(supported_format);
+            DVLOG(1) << VideoCaptureFormat::ToString(supported_format);
+          }
+        }
+        break;
       }
 
       const std::vector<float> frame_rates = GetFrameRateList(
`

**Comment by jc-kynesim** [comment]
`Testing
- this didn't work last time`

**Comment by jc-kynesim** [comment]
OK - sorry if you got notifications about previous comments - I tried and failed to get a raw patch in the comments but it turned into a bulleted list - hopefully a text file will work.  Patch from v95.

[camera.txt](https://github.com/RPi-Distro/chromium-browser/files/7829777/camera.txt)

**Comment by andi34** [comment]
Great! Thanks a lot! You've got a link to the official Debian port?

**Comment by jc-kynesim** [comment]
No. but "apt-get source chromium" should do the trick  along with "sudo apt-get build-dep chromium".  Note I've never done that myself - I've always used git to grab from google - there are instructions on how to build from there if you search but the full debian build might be more reliable.

**Comment by andi34** [comment]
I've compiled from the Google sources in the past for Android. Would an normal build be enough to work?

Edit:
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md

```
gn gen '--args=target_cpu="x86" is_debug=false symbol_level=0 enable_nacl=false remove_webcore_debug_symbols=true proprietary_codecs=true ffmpeg_branding="Chrome"' out/Default

autoninja -C out/Default chrome
```

Edit 2:
Just seen

> Mac and desktop Linux supports only  "x64". On desktop Linux you might also theoretically try any of the ARM or MIPS architecture strings form the Android section below, but these aren't supported or tested and you will also need a sysroot.

Debian without Desktop would work?

**Comment by jc-kynesim** [comment]
If you are compiling for Pi then you need target to be arm not x86 - cross compile does work (it is what I do)

**Comment by andi34** [comment]
Thanks! So I would go with `apt-get source chromium` to get the arm related patches, official chromium sources don't seem to have them.

**Comment by XECDesign** [comment]
@cillian64 Would you happen to know what the camera situation is nowadays? Do you think this is resolved?

**Comment by jc-kynesim** [comment]
Chrome camera stuff creased working when simple camera V4L2 support went away in the kernel. I don't think anything has been done since then. It is possible that Chrome now knows enough pipewire that support via that might be doable but I don't know.

Firefox is your friend if you want camera support in a browser currently.

**Comment by cillian64** [comment]
In chromium, if you navigate to `chrome://flags`, search for "pipewire", enable `PipeWire Camera Support`, then restart chromium, then imx477 works for me on a Pi4. (Apparently as-of chromium 127/128).

However, I don't want to officially support this: upstream don't consider it stable (which is why it's behind a flag) and we haven't made any downstream changes, so if it stops working again I will blame upstream.

**Comment by XECDesign** [comment]
Just pushed a new chromium package which enabled PipeWire Camera support by default.

Please note that Chromium may remove or break the option in future releases. If that happens, we will not be maintaining this feature. 

If this is for something more critical than personal use, switching to Firefox may be a safer bet.

**Comment by XECDesign** [comment]
Looks like this change breaks things in some cases. https://forums.raspberrypi.com/viewtopic.php?p=2263659

**Comment by jwoillez** [comment]
I have the same issue as reported in the link above by @XECDesign . Note that disabling pipewire camera is also needed in firefox 132.0 to make it work there as well.

**Comment by cillian64** [comment]
> I have the same issue as reported in the link above by @XECDesign . Note that disabling pipewire camera is also needed in firefox 132.0 to make it work there as well.

Please could you let me know what webcam you're using?  We've not been able to reproduce this issue so we're trying to work out if it's specific to certain webcams or something else in the environment.

**Comment by jwoillez** [comment]
In my case, this is a Logitech Brio 100, a USB camera. Happy to provide more information.

**Comment by cillian64** [comment]
Thanks, I've ordered one of those and I'll see if I can reproduce the problem.

**Comment by cillian64** [comment]
@jwoillez I've just tested with the Logitech Brio 100 and it's working fine for me in Chromium.  This is with the latest chromium (1:130.0.6723.116-1~deb12u1+rpt1) and rpi-chromium-mods (20240904).

I was testing with a clean profile.  Would you be able to try testing with a clean chromium profile?  I don't recommend doing this unless you are okay with losing all your bookmarks/history/saved logins/everything else.  You can either delete `/.config/chromium`or just temporarily rename it.  Or, if you have a spare microSD card, you could try a clean install of raspberry pi OS.

Otherwise, could you try testing with https://mozilla.github.io/webrtc-landing/gum_test.html (the "Camera" button) just in case it's something specific to the website you're using?

**Comment by hirs0105pi** [comment]
I want to use google meet on Raspberry pi 5 (Bookworm) using web camera and microphone .

I was very helpful for the information which chromium v88 later can not recognize webcam on this forum. 
Thus changed the browser from Chromium to Firefox, Firefox 134.0.1 could detect my web camera (FHD Camera Microphone).

However I can not connect to web camera still . Firefox displays permission denied or blocked on setting page.
Google meet and https://webrtc.github.io/samples/ etc are failed at permission.

At first, microphone in the web camera also could not connect by permission denied. But after turn on and off the switch of SPI and I2C on raspberry pi configure, the microphone can detect and use on  Firefox now.

I already have added user(pi) to the video group by usermod command and confirmed video group includes pi by groups pi and getfacl /dev/video0.

$v4l2-ctl --list-devices outputs /dev/video0 , video1 and media3.
FHD Camera Microphone: FHD Came (usb-xhci-hcd.1-1):
       /dev/video0
        /dev/video1
        /dev/media3

$ls -l /dev/video0
crw-rw----+ 1 root video 81, 17 Jan 27 11:07 /dev/video0

$ getfacl /dev/video0
getfacl: Removing leading '/' from absolute path names
file: dev/video0
owner: root
group: video 
user::rw-
user:pi:rw-
group::rw-
mask::rw-
other::---

What block the connection of web camera?
Please help me.

**Comment by cillian64** [comment]
Please could you try deleting or renaming `~/.local/share/flatpak/db/devices`, then reboot

**Comment by hirs0105pi** [comment]
Thank you for your reply.
Before your advice ,I tried to use initial SD card installed Raspberry pi OS(64 bit) and confirmed to go camera and microphone on Firefox.
Your guess is correct, the root cause of the permission denied is likely a mismatch in application dependencies by my past setting.

**Comment by hirs0105pi** [comment]
Thank you very much.
By change to the old sd card and deleting  ~/.local/share/flatpak/db/devices ,confirmed to access camera and microphone.
I'm glad to use every setting which set at past too.

**Comment by cillian64** [comment]
Thanks for confirming
