### ISSUE TITLE
Audio renderer error while running youtube through selenium

### ISSUE THREAD

**Issue by sijumanuel** [RPi-Distro/chromium-browser#24]
Audio renderer error :Please restart your computer while trying to open youtube using selenium.
It was working fine till last week.
Please find the code snippet below

service = Service("/usr/lib/chromium-browser/chromedriver")
 driver=webdriver.Chrome(service=service)
time.sleep(2) 
driver.get('https://youtu.be/YUvVmN99sE4')

**Comment by XECDesign** [comment]
Not seeing an issue with the following example:

```
#!/usr/bin/python3

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import time

service = Service("/usr/lib/chromium-browser/chromedriver")
driver=webdriver.Chrome(service=service)
time.sleep(2)
driver.get('https://youtu.be/yWRvE-DcX64')
```

More information needed to reproduce the issue.
