### ISSUE TITLE
Full screen indication does not work

### ISSUE THREAD

**Issue by usr** [RPi-Distro/chromium-browser#31]
Tested on 32 bit version of Raspbian 10, Chromium version 92.0.4515.98. Hope to be able to test this on an up to date 64bit version of Raspberry Pi OS in the coming days.

When starting Chromium with the --kiosk parameter it starts in full screen mode correctly. However when this full screen state of the browser is checked using JavaScript the state is incorreclty reported as not full screen.

The check performed:
      return document.fullscreenElement || /* Standard syntax */
        document.webkitFullscreenElement || /* Safari and Opera syntax */
        document.webkitIsFullScreen || /* Safari and Opera syntax */
        document.webkitFullScreen || /* Safari and Opera syntax */
        document.msFullscreenElement || /* IE11 syntax */
        document.msFullscreen || /* IE11 syntax */
        document.mozFullScreenElement || /* Firefox syntax */
        document.mozFullScreen || /* Firefox syntax */
        document.fullscreen; /* Standard obsolete syntax, just in case */

A number of these attributes will be undefined since they are meant for non Chromium based browsers but none of the variables that is supposed to be true and that are true on Chromium that run on other Debian based versions of Linux is true.

Workaround for those that have the same issue:

($(window).width() == window.screen.width && $(window).height() == window.screen.height)

will return true when Chromium is started with the --kiosk option.

**Comment by XECDesign** [comment]
Sorry, this repo is just for issues related to our specific build of chromium. This does not look related to area of chromium we've modified, nor is our build of chromium supported in Buster.
