### ISSUE TITLE
Hardware accelerated Chromium on CM3+ does not render correctly

### ISSUE THREAD

**Issue by JinShil** [RPi-Distro/chromium-browser#35]
For context, please see https://forums.raspberrypi.com/viewtopic.php?t=337558

Pi Hardware: CM3+
OS: Latest 32-bit Raspberry Pi OS Bullseye downloaded today
Browser version: Chromium 101.0.4951.57 Built on Raspbian , running on Raspbian 11

View the graphics demo at https://pixijs.io/examples/#/demos-basic/blendmodes.js on any desktop PC as a reference for what it should look like.

On a CM3+, using `dtoverlay=vc4-kms-v3d`, and with Glamor enabled, the demo looks like this:

![image](https://user-images.githubusercontent.com/6023641/180893399-88fd728e-335e-4264-8a54-3111a3d945d2.png)

The speed at which the sprites move indicates the hardware acceleration pipeline is being utilized, but the graphics are just not rendered correctly.

Disabling Glamor, and adding command line arguments `--use-gl=angle --use-angle=gl-egl --use-cmd-decoder=passthrough` seems to work around the issue.  The workaround does not work if Glamor is enabled, which is quite curious.

The demo functions correctly on the CM4.

**Comment by XECDesign** [comment]
@naushir

**Comment by jasuarez** [comment]
This is [fixed in Mesa upstream](https://gitlab.freedesktop.org/mesa/mesa/-/commit/4ba21c3e8cef567f0c39460dd3f1d20f754c3c6f).

**Comment by XECDesign** [comment]
@spl237 Can this be backported to our version?

**Comment by JinShil** [comment]
This is no longer an issue with the latest OS releases.
