### ISSUE TITLE
Chromium Distored sound only on HDMI Output

### ISSUE THREAD

**Issue by SNRSE** [RPi-Distro/chromium-browser#37]
Hey, 
I am currently encountering an issue where files are being played in chromium and have a distorted sound when listening over HDMI, 
it does not appear to be there when using the Jack Output.
also, the same I and setup. If I use VLC it sounds fine as well.
Here are my records showing the issue:
https://we.tl/t-XDsHafxYOp

**Comment by XECDesign** [comment]
Is this still an issue?
