### ISSUE TITLE
Bug: Google account requires sign-in everytime I open browser

### ISSUE THREAD

**Issue by hubby4** [RPi-Distro/chromium-browser#45]
Since the Raspberry Pi OS (64-bit) package manager updated to this new version (128.0.6613.119)  of Chromium, I can no longer stay signed in to my google account.

What I tried:

1) I first tried clearing all cache, cookies, and sign-in data and restart.
2) When that didn't work, I deleted my profile.
3) When that didn't work, I used sudo apt purge chromium, deleted the ~/.config/chromium folder, and reinstalled chromium.

None of these worked. Sign-in works fine with Firefox.

**Comment by XECDesign** [comment]
@cillian64 @jc-kynesim

**Comment by cillian64** [comment]
Thanks for the bug report.  As a workaround, disabling "Settings" -> "sync and google services" -> "allow chromium sign-in" makes the problem go away for me.  We'll try to get this fixed in a patch release soon.

**Comment by XECDesign** [comment]
Just uploaded a new version which seems to fix the problem for me, thanks to a patch from @cillian64.

**Comment by hubby4** [comment]
It's now working for me. Thank you.
