### ISSUE TITLE
After a recent update, the browser crashes frequently when graphics acceleration is enabled

### ISSUE THREAD

**Issue by edgerunning** [RPi-Distro/chromium-browser#48]
It used to work fine until an update about a month ago. Now, whenever I highlight something and then right-click, the browser crashes. I don't know what caused this, but if I disable graphics hardware acceleration in the browser settings, it works fine and never crashes. It used to work fine no matter whether hardware acceleration was enabled or not.
I'm using the default desktop environment of Raspberry Pi OS Bookworm, with the scaling factor set to 2 in ~/.config/wayfire.ini

This is the error that occurs when it crashes.
```
[2338756:2338756:1010/033630.844794:ERROR:wayland_event_watcher.cc(47)] libwayland: xdg_wm_base#15: error 4: wrong configure serial: 180291

[1010/033630.856032:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

Chromium version I installed
```
chromium-common/stable,stable,now 1:129.0.6668.89-1deb12u1+rpt2 arm64 [installed,automatic]
chromium-l10n/stable,stable,stable,stable,now 1:129.0.6668.89-1deb12u1+rpt2 all [installed,automatic]
chromium-sandbox/stable,stable,now 1:129.0.6668.89-1deb12u1+rpt2 arm64 [installed,automatic]
chromium/stable,stable,now 1:129.0.6668.89-1deb12u1+rpt2 arm64 [installed]
rpi-chromium-mods/stable,stable,now 20240904 arm64 [installed]

```
https://github.com/user-attachments/assets/3e746807-440d-4034-bbf2-cd30b2b39d17

**Comment by XECDesign** [comment]
Are you still seeing this with .100? Which pi are you using and is there a reliable way to reproduce the issue?

On a pi5 running the latest version under wayfire, if I do the same thing as in your video, it works as expected.

**Comment by edgerunning** [comment]
> Are you still seeing this with .100?

Yes, I updated to the latest `1:129.0.6668.100-1~deb12u1+rpt1`, but the problem still persists. I also tried labwc, and the issue exists there too, not just with Wayfire.

> Which pi are you using and is there a reliable way to reproduce the issue?

I am using pi 5.
If Under labwc, I run the command `wlr-randr --output HDMI-A-1 --scale 2` to scale it to 2x; you may need to specify a different output. If under Wayfire, I set the scale factor in ~/.config/wayfire.ini. like 
```
[output:HDMI-A-1]
mode = 3840x2160@60000
position = 0,0
transform = normal
scale = 2.0
```
In Chromium, if you open a website, select a clickable hyperlink, and then right click, it crashes.
The problem doesn't occur if you either turn off the '`Use graphics acceleration when available`' option or don’t scale to 2x.

**Comment by XECDesign** [comment]
Tried under labwc with `wlr-randr --output HDMI-A-1 --scale 2`, still not seeing the problem. We've still got some difference somewhere.
