### ISSUE TITLE
Chromium 130 from rpi repo doesn't respect the 90° FOV set on BRIO webcam and streams in 78° FOV

### ISSUE THREAD

**Issue by mghadam** [RPi-Distro/chromium-browser#53]
**Description**
Chromium 130 from RaspberryPi repo doesn't respect the 90° FOV set on BRIO webcam and streams in 78° FOV. See attached screenshots.
<img width="1413" alt="chromium130frpmRPI-78FOV" src="https://github.com/user-attachments/assets/d1509da1-1095-403e-b423-1092181ce73f">

**Expected Behaviour** 
Chromium 130 from RPI should also stream in 90FOV as the upstream version from debian or v129 from rpi repo do. 

<img width="1405" alt="chromium130fromdebian-90FOV" src="https://github.com/user-attachments/assets/2197ae69-90e8-4626-bc6b-ae398887caa4">

**Steps to reproduce the problem**
Upgrade chromium to v129 to v130
Launch a meeting in any streaming platform (tested on Google meet, Jitsi and Skype)
Chromium crops camera input and stream in square 78° rather than wide 90° set on camera as per attached pictures. 

**Does this work in other browsers?**
Yes - This is just a Chromium v130 from rpi repo problem. 
Firefox, Chromium 129 from rpi repo and last version of chromium from debian repo `130.0.6723.91-1~deb12u1` do not have this issue.  The current version of chromium from raspberry pi `130.0.6723.91-1~deb12u1+rpt2` has this issue as well as previous v130 versions from rpi repo.

**Contents of chrome://gpu and chrome://version/?show-variations-cmd**
Reports for both chromium `130.0.6723.91-1~deb12u1` from debian without this issue, and for `130.0.6723.91-1~deb12u1+rpt2` from rpi repo are attached:

[chromium-gpu-130-deb-90FOV.txt](https://github.com/user-attachments/files/17689652/chromium-gpu-130-deb-90FOV.txt)

[chromium-gpu-130-rpi-78FOV.txt](https://github.com/user-attachments/files/17689651/chromium-gpu-130-rpi-78FOV.txt)

[chromium-variations-130-debian-90FOV.txt](https://github.com/user-attachments/files/17689650/chromium-variations-130-debian-90FOV.txt)

[chromium-variations-130-rpi-78FOV.txt](https://github.com/user-attachments/files/17689649/chromium-variations-130-rpi-78FOV.txt)

**Comment by XECDesign** [comment]
Does disabling "PipeWire Camera Support" in chrome://flags fix the issue?

**Comment by mghadam** [comment]
Thank you! Yes, disabling `PipeWire Camera Support` in `chrome://flags` resolved the issue.

**Comment by XECDesign** [comment]
How do you select the FOV to use on those cameras? Is it a physical selector of some kind or some software you run?

**Comment by mghadam** [comment]
The FOV can be adjusted using the camera's proprietary software, but there is no setting to modify it through `v4l2-ctl` or read the current FOV. When the FOV is set to 90 degrees, the output appears wide in almost any streaming software. However, enabling the `PipeWire Camera Support` setting seems to force a near square streaming output, which crops the sides of the camera stream, making it look like the output is narrower.

**Comment by XECDesign** [comment]
Okay, not much that can be done on our end then.
