### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by g1gsw** [RPi-Distro/chromium-browser#8]
When I try to install the latest gmail notifier it tells me that chromium is out of date and does not work.  If I leave it open on the desktop for a while google keeps informing me that it is out of date.

**Comment by XECDesign** [comment]
There seems to be a number of things that call themselves gmail notifier. Do you have a link to what you're using and how you installed it?

**Comment by g1gsw** [comment]
Hi here is the link.

https://chrome.google.com/webstore/detail/checker-plus-for-gmail/oeopbcgkkoapgobdbedcemjljbihmemj?utm_source=chrome-ntp-icon

Colin

**Comment by XECDesign** [comment]
I don't see any information there to see how it determines what's too old. I found a page where he says he only supports the 'stable' version of chromium, but not much else. It doesn't look like anything we can fix on our end, unfortunately.
