### ISSUE TITLE
Up-to-date RPI OS chromium browser patches to download?

### ISSUE THREAD

**Issue by systemq2** [RPi-Distro/chromium-browser#9]
Hi there,

I'd like to use the CEF library with mmal patches for the chromium browser applied on RPI 3b+ for my project. Unfortunately the latest patch version published in this repository is 78.0.3904.108 whereas the chromium browser version in the current RPI OS is 84.0.4147.141. Would it be possible to publish up-to-date RPI patches for chromium browser to give other people a chance to build a mmal-enabled libcef and use the hardware decoding capability of the RPI hardware?

**Comment by XECDesign** [comment]
Added https://github.com/RPi-Distro/chromium-browser/blob/master/debian/patches/v84.0.4147.141_mmal_3.31.patch and the other patches used for that build.

**Comment by systemq2** [comment]
Thank you, XECDesign. I appreciate that and your contribution to the RPI project in general.

**Comment by XECDesign** [comment]
Thank you. The real work here was done by jc-kynesim, the firmware and kernel devs, but I'll gladly take the credit.
